name: Build app_python

on:
  push:
    paths:
    - 'app_python/**'
    - '.github/workflows/app_python.yaml'
  pull_request:
    paths:
    - 'app_python/**'
    - '.github/workflows/app_python.yaml'

jobs:
  lint:
    timeout-minutes: 2
    name: Run black linter
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  test:
    timeout-minutes: 2
    defaults:
      run:
        working-directory: app_python
    name: Run pytest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          PYTHONPATH=. pytest

  snyk_check:
    needs: [lint, test]
    timeout-minutes: 5

    name: Run SNYK
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        with:
          args: --skip-unresolved app_python/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build_push:
    timeout-minutes: 10
    defaults:
      run:
        working-directory: app_python
    needs: [lint, test, snyk_check]
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push to the dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/app_python:latest"
          context: "{{defaultContext}}:app_python"
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/app_python:latest
          cache-to: type=inline
